version: '3'
services:
 nginx-proxy:
  image: docker.pkg.github.com/laiyefei/hub/nginx:latest
  container_name: nginx
  ports:
   - 9999:80
  volumes:
   - ~/laiyefei/datas/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
