version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    volumes:
      - ~/.laiyefei/datas/minio:/data
    ports:
      - "9999:9000"
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: laiyefei
      MINIO_ROOT_PASSWORD: laiyefei
      MINIO_PROMETHEUS_AUTH_TYPE: public
    command: server /data
    networks:
      - minio

networks:
  minio:
    driver: bridge