version: '3'
services:
  mysql:
    image: docker.pkg.github.com/laiyefei/hub/mysql:8.0.27
    container_name: mysql
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    restart: always
    volumes:
      - ~/.laiyefei/datas/mysql:/var/lib/mysql/
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=laiyefei
