version: '3.1'
networks:
  nginx:
    driver: bridge
services:
  nginx:
    container_name: nginx
    image: docker.pkg.github.com/laiyefei/hub/nginx:latest
    restart: always
    ports:
      - 80:80
    networks:
      - nginx
    privileged: true
    volumes:
      - ~/laiyefei/datas/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/laiyefei/datas/nginx/conf.d:/etc/nginx/conf.d
      - ~/laiyefei/datas/nginx/html:/usr/share/nginx/html
      - ~/laiyefei/datas/nginx/log:/var/log/nginx