version: '3.3'
services:
  pgadmin4:
    image: docker.pkg.github.com/laiyefei/hub/pgadmin:latest
    ports:
      - 800:80
    environment:
      PGADMIN_DEFAULT_EMAIL: laiyefei@feels.tech
      PGADMIN_DEFAULT_PASSWORD: laiyefei

