version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ~/laiyefei/datas/redis/data:/data
      - ~/laiyefei/datas/redis/redis.conf:/usr/local/etc/redis/redis.conf
