version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.13.2
    container_name: elk_elasticsearch
    restart: on-failure
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    networks:
      - elk
    volumes:
      - ~/.laiyefei/datas/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ~/.laiyefei/datas/elk/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:7.13.2
    container_name: elk_kibana
    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - elk
    environment:
      SERVER_PORT: 5601
      I18N_LOCALE: zh-CN
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_SECURITY_ENCRYPTIONKEY: D8824EC9409B44E28908D4CFBC1E9872
    ports:
      - 5601:5601
  logstash:
    image: logstash:7.13.2
    container_name: elk_logstash
    restart: on-failure
    volumes:
      - type: bind
        source: "./logstash_stdout.conf"
        target: "/usr/share/logstash/pipeline/logstash.conf"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
    ports:
      - 9600:9600
      - 5044:5044
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.2
    container_name: filebeat
    hostname: filebeat
    restart: on-failure
    volumes:
      - type: bind
        source: "./filebeat.yml"
        target: "/usr/share/filebeat/filebeat.yml"
    networks:
      - elk
    depends_on:
      - logstash
networks:
  elk:
    driver: bridge

## Q.A.
# Q: License is not available
# A: 可能是由于docker的内存限制过小